// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEsTT-HVY97dBmqs5Ww372PvGm0ylwmeE',
    appId: '1:262782523022:web:880665d6ebea09e4f95bdf',
    messagingSenderId: '262782523022',
    projectId: 'kpkasirbj',
    authDomain: 'kpkasirbj.firebaseapp.com',
    storageBucket: 'kpkasirbj.firebasestorage.app',
    measurementId: 'G-D586GH3V4Q',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEsTT-HVY97dBmqs5Ww372PvGm0ylwmeE',
    appId: '1:262782523022:web:038f821ed5caa239f95bdf',
    messagingSenderId: '262782523022',
    projectId: 'kpkasirbj',
    authDomain: 'kpkasirbj.firebaseapp.com',
    storageBucket: 'kpkasirbj.firebasestorage.app',
    measurementId: 'G-TB8SQ9QEH1',
  );
}
